### ISSUE TITLE
Mình muốn trao đổi với bạn về tool tự động dịch truyện tiếng Trung

### ISSUE THREAD

**Issue by davidtrse** [n-pn/chivi#13]
Hi bạn, mình có thể trao đổi với bạn về tool tự động dịch truyện tiếng trung được không? 

mình là developer, mình rành golang nhưng ko rành C# nên không đọc được code của quicktranslator.

mình biết bạn đang làm tool để dịch. mình rất muốn trao đổi với bạn. 

Telegram của mình: https://t.me/minhtranse

**Comment by n-pn** [comment]
Đã liên hệ qua fb.
